version: "3.4"
services:
  product-mongodb:
    container_name: product-mongodb
    image: mongo
  product-integration-tests:
    container_name: product-integration-tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - ProductDatabaseSettings__ConnectionString=mongodb://product-mongodb:27017
    volumes:
      - .:/src
    working_dir: /src/Product.API.IntegrationTests
    command:
      [
        "dotnet",
        "test",
        "Product.API.IntegrationTests.csproj"
      ]
    depends_on:
      - product-mongodb
