name: Product API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# defaults:
  # run:
    # working-directory: src/product-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal --filter UnitTests
    - name: Execute integration tests
      # working-directory: ./src
      run: docker-compose --file docker-compose-integration.yml up --exit-code-from integration-tests